# Note: Smaller values result in less lag. Lift speed less than 0.4 may not work well for non spout servers.
maxLiftArea: 16
debug: false
autoPlace: false
checkGlass: false
floorBlock: GLASS
baseBlockSpeeds:
  IRON_BLOCK: 0.5