author: croxis
database: false
description: Elevators
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.croxis.plugins.lift.Lift
name: Lift
startup: postworld
version: '1.0'
depend: [Spout]