author: croxis
database: false
description: Elevators
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.croxis.plugins.lift.Lift
name: Lift
startup: postworld
version: '13'
softdepend: [Spout, V10verlap]