author: croxis
database: false
description: Elevators
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.croxis.plugins.lift.Lift
name: Lift
startup: postworld
version: '20'
softdepend: [Spout,AntiCheat]
permissions:
  lift:
    description: Can ride in a lift
    default: true